os: osx
language: clojure
deploy:
  provider: releases
  api_key:
    secure: 3xIPPkDWvHaD7Fnc/g/mmPoYb4pxcS+iZ5PtcH421Sulfuk5b8+dG64uZ+YfKpyUTuGgvnI2Fe70Ne1kku/+AJuljBBCivqb8LED4cO4+5eJYQa95YUyhtIWpxdykdexYCzLa7AFWGx1UsFvk+XU5O7WKLJxNvPKmaJ9bcWrnhm4XH94u5qICQqav4PAoSoWqRF2gK/hBqQSNDW7Voz5VS1YQUEmxoX0OoSHQGaDn0juxJzprFi/W/0aapEOPSd+G7OQ6D34ShRVQ6DBxI8t+1urm3prz0kNqum/5u+KFKXKfBkH17MmWiQIn0cQsNS/UV6T2j61XHjA3+g5HRX4Jwm7mBV3UMDASaeNvMdb3i/3zLosX74jgVDjRrm0P10U7N3UTOORmMrRI3YzOjPWluQFabGU0yplOnQ36Gw3K/++VTPmBXdY3UukATOsZ7ymO6KTAIOleOQlsqVr1sB6IrDViuCzVGpYEXNk5FaM0B13T1svY3ObANxlPITDSKgtv+cmbbzV6WHKYfBetpQV2h3Ske5LADAF4hswaNiRH7njE3ARoEBqz8nZ7pBM9gtAbzxABXyPmTjVYMZn6KekZcvqCyPHHxe0j/PzxLLbkOcFfY3Il6iNLSAAMZj+yszT4Fh/ibM3UQmDoy8zQCcfIWTF5ACXWzCw9cjn6/0Sc+M=
  file: "goku.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    repo: yqrashawn/GokuRakuJoudo
before_install:
- sh scripts/travis.sh
# - wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc13/graalvm-ce-1.0.0-rc13-macos-amd64.tar.gz
- brew install candid82/brew/joker
- curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
- ~/.jabba/bin/jabba install graalvm@19.2.1
# - tar xf graalvm-ce-1.0.0-rc13-macos-amd64.tar.gz
- ~/.jabba/jdk/graalvm@19.2.1/Contents/Home/bin/gu install native-image
- export PATH=$PATH:$HOME/.jabba/jdk/graalvm@19.2.1/Contents/Home/bin/
script:
- lein test
- make
- make test-binary
- touch gokuw
- echo '#!/bin/sh' >> gokuw
- echo 'watchexec -r -w ~/.config/karabiner.edn /usr/local/opt/goku/bin/goku' >> gokuw
- "./goku"
- chmod +x gokuw
- tar czf goku.tar.gz goku gokuw
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/Library/Caches/Homebrew"
  - "/usr/local/Cellar/leiningen/"
  - "/usr/local/Cellar/watchexec/"
after_success:
- lein cloverage --no-html --coveralls
- curl -F json_file=@./target/coverage/coveralls.json https://coveralls.io/api/v1/jobs
