os: osx
language: clojure
before_install:
  - brew install watchexec
  - brew install leiningen
  - wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc6/graalvm-ce-1.0.0-rc6-macos-amd64.tar.gz
  - tar xf graalvm-ce-1.0.0-rc6-macos-amd64.tar.gz
  - export PATH=$PATH:$PWD/graalvm-ce-1.0.0-rc6/Contents/Home/bin/
script:
  - lein test
  - make test
  - ./goku
  - ./goku -w